config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'
  root "posts#index"

  get "home/index"
  get "posts/new"
  post "posts/create"
  get "posts/index"

  get "posts/show/:id" => "posts#show"
  get "posts/edit/:id" => "posts#edit"
  post "posts/update/:id" => "posts#update"
  get "posts/destroy/:id" => "posts#destroy"

  post "posts/:id/comments" => "comments#create", as: "posts_comments_create"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    post = Post.find(params[:id]) #id -> post의 id 값 

    comment = Comment.new
    comment.user_name = params[:user_name]
    comment.body = params[:body]
    comment.post_id = params[:id]

    comment.save

    redirect_to request.referrer
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all # Post모델 전체를 가지고온다. 이 all의 의미는 선택할 수 있는 의미가 아닌 모든 것을 말한다.
  end

  def new
  end

  def create
    @post = Post.new
    @post.title = params[:title] #모델 컬럼 정보와 뷰에서 넘겨온 form action으로 넘어온 hash 심볼 title 키를 매칭시켜준다. new.html.erb에서 post방식으로 보내온 name="title"을 params로 모델 컬럼 @post(=Post.new).title 연결
    # => #<Post id: nil, title: "wonno", content: nil, created_at: nil, updated_at: nil>
    @post.content = params[:content] #모델 컬럼 정보와 매칭시켜준다. new에서 가지고온 name="content"을 params로 모델 컬럼 @post(=Post.new).content 연결
    @post.save #컬럼에 입력된 정보를 post 모델에 저장 한다.

    redirect_to "/posts/index"
  end

  def show
    @post = Post.find(params[:id]) # 라우터에서 보내온 id를 기준으로 Post 모델에서 id 값을 기준으로 찾을 수 있다.
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    @post.title = params[:title]
    @post.content = params[:content]

    @post.save

    redirect_to "/posts/index"
  end

  def destroy
    @post = Post.find(params[:id])

    @post.destroy

    redirect_to "/posts/index"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestCrud</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<form action="/posts/update/<%= @post.id %>" method="POST">
	<input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
	<input type="text" name="title" value="<%= @post.title %>">
	<input name="content" value="<%= @post.content %>">
	<button type="submit">수정</button>
</form>

app/views/posts/index.html.erb
<a href="/posts/new">새글 작성 하기</a><br>
<% @posts.each do |post| %>
	title : <%= post.title %>
	content : <%= post.content %>
	<a href="/posts/show/<%= post.id %>"> 이 동 </a>
	<hr>
<% end %>

app/views/posts/new.html.erb
<form action="/posts/create" method="POST">
	<input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
	<input type="text" name="title">
	<input name="content">
	<button type="submit">제출</button>
</form>

app/views/posts/show.html.erb
<%= @post.id %>의 글
<hr>
title : <%= @post.title %>
<hr>
content : <%= @post.content %>
<hr>
<a href="/posts/edit/<%= @post.id %>"> 수 정 </a>
<a href="/posts/destroy/<%= @post.id %>"> 삭 제 </a>
<a href="/posts/index">홈으로가기</a>

<form action="<%= posts_comments_create_path(@post) %>" method="POST">
	<input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
	작성자 : <input type="text" name="user_name">
	댓글 : <input type="text" name="body">
	<button type="submit">제출</button>
</form>
<hr>

댓글 보기
<hr>
<% Comment.where(post_id: @post.id).each do |comment| %>
	작성자 : <%= comment.user_name %>
	댓글 : <%= comment.body %>
	<hr>
<% end %>